#pragma once

#include <StraveEngine/Config.hpp>


#if defined(STRAVE_SYSTEM_EXPORTS)

	#define STRAVE_SYSTEM_API		STRAVE_API_EXPORT
	#define STRAVE_ENTITY_API		STRAVE_API_EXPORT
	#define STRAVE_COMPONENT_API	STRAVE_API_EXPORT
	#define STRAVE_ELEMENT_API		STRAVE_API_EXPORT
	#define STRAVE_GRAPHICS_API		STRAVE_API_EXPORT
	#define STRAVE_CONTROL_API		STRAVE_API_EXPORT

#else

	#define STRAVE_SYSTEM_API STRAVE_API_IMPORT

#endif
